name: bibliometrics

on:
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v6

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: 'Download and run bibliometrics'
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade bibliometrics
        python3 -m bibliometrics
      env:
        SCHOLAR_ID: ${{ secrets.SCHOLAR_ID }}
        USER_AGENT_BIB: ${{ secrets.USER_AGENT_BIB }}

    - name: Commit and push the bibliometrics SVGs and JSON
      run: |
        if [[ `git status --porcelain bibliometrics.json` ]]; then
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add bibliometrics.json images/bibliometrics.svg images/bibliometrics2.svg
          git commit -m "Autogenerated bibliometrics" bibliometrics.json images/bibliometrics.svg images/bibliometrics2.svg
          git push
        fi
